const fs = require('fs');
const path = require('path');

const jaPath = path.resolve(__dirname, '..', 'src', 'main', 'resources', 'items', 'ja.json');
const raw = fs.readFileSync(jaPath, 'utf8');
const lines = raw.split(/\r?\n/).map(l => l.trim()).filter(l => l && !l.startsWith('//'));

// Mapping japonais -> { translation, level }
const map = {
  "だ": ["(copule) être", 1],
  "する": ["faire", 1],
  "です": ["être (poli)", 1],
  "いる": ["être (existence pour êtres animés)", 1],
  "私": ["je / moi", 1],
  "ある": ["il y a / avoir", 1],
  "こと": ["chose / fait", 1],
  "何": ["quoi", 1],
  "それ": ["cela / ça", 1],
  "なる": ["devenir", 2],
  "この": ["ce / cette", 1],
  "これ": ["ceci / celui-ci", 1],
  "そう": ["ainsi / comme ça", 1],
  "言う": ["dire", 1],
  "彼": ["il / lui", 1],
  "どう": ["comment", 1],
  "いい": ["bon", 1],
  "人": ["personne / personne", 1],
  "あなた": ["vous / tu", 1],
  "俺": ["je (informel masculin)", 2],
  "その": ["ce / celui-là", 1],
  "君": ["tu (informel)", 2],
  "やる": ["faire / donner (familier)", 2],
  "見る": ["voir", 1],
  "行く": ["aller", 1],
  "いう": ["dire (variante)", 1],
  "くれる": ["donner (à moi)", 2],
  "できる": ["pouvoir / savoir faire", 1],
  "ここ": ["ici", 1],
  "お前": ["toi (rude)", 3],
  "知る": ["savoir / connaître", 2],
  "来る": ["venir", 1],
  "もう": ["déjà / encore", 1],
  "誰": ["qui", 1],
  "今": ["maintenant", 1],
  "者": ["personne / celui qui...", 2],
  "けど": ["mais (colloquial)", 1],
  "彼女": ["elle / petite amie", 1],
  "僕": ["je (masculin, informel)", 2],
  "あの": ["ce... / celui-là (loin)", 1],
  "分かる": ["comprendre", 2],
  "年": ["année", 1],
  "中": ["à l'intérieur / milieu", 2],
  "前": ["avant", 1],
  "時": ["temps / heure", 1],
  "聞く": ["écouter / demander", 2],
  "自分": ["soi-même", 2],
  "つく": ["attacher / arriver", 3],
  "持つ": ["tenir / posséder", 2],
  "どこ": ["où", 1],
  "そして": ["et puis", 1],
  "話": ["histoire / parole", 2],
  "そんな": ["tel / ainsi", 1],
  "出る": ["sortir / apparaître", 2],
  "必要": ["nécessaire", 2],
  "なん": ["quoi (colloquial)", 1],
  "話す": ["parler", 1],
  "待つ": ["attendre", 1],
  "出す": ["sortir / donner", 2],
  "方": ["façon / direction", 2],
  "一": ["un", 1],
  "考える": ["penser", 2],
  "家": ["maison", 1],
  "死ぬ": ["mourir", 3],
  "気": ["esprit / sentiment", 2],
  "時間": ["temps", 1],
  "ちょっと": ["un peu", 1],
  "本当": ["vrai", 2],
  "我々": ["nous", 3],
  "はい": ["oui", 1],
  "まだ": ["encore / toujours", 1],
  "くださる": ["donner (honorifique)", 4],
  "そこ": ["là", 1],
  "日": ["jour", 1],
  "世界": ["monde", 2],
  "良い": ["bon", 1],
  "みる": ["voir (variante)", 1],
  "なぜ": ["pourquoi", 1],
  "使う": ["utiliser", 1],
  "大丈夫": ["ça va / sans problème", 1],
  "後": ["après", 1],
  "こんな": ["tel / comme ça", 1],
  "男": ["homme", 1],
  "他": ["autre", 2],
  "手": ["main", 1],
  "仕事": ["travail", 2],
  "問題": ["problème", 2],
  "また": ["encore / de nouveau", 1],
  "同じ": ["même", 1],
  "入る": ["entrer", 1],
  "違う": ["différent", 2],
  "一緒": ["ensemble", 1],
  "会う": ["rencontrer", 2],
  "様": ["manière / Mr/Mme (suff.)", 3],
  "作る": ["faire / créer", 2],
  "みたい": ["semble / comme", 2],
  "戻る": ["revenir", 2],
  "今日": ["aujourd'hui", 1],
  "悪い": ["mauvais", 1],
  "見つける": ["trouver", 2],
  "子": ["enfant", 2],
  "あんた": ["toi (familier)", 3],
  "みんな": ["tout le monde", 1],
  "すぐ": ["immédiatement", 1],
  "電話": ["téléphone / appel", 1],
  "しかし": ["cependant", 2],
  "もし": ["si", 1],
  "人間": ["être humain", 2],
  "場所": ["endroit", 2],
  "なさる": ["faire (honorifique)", 4],
  "所": ["endroit", 2],
  "子供": ["enfant", 1],
  "力": ["force", 2],
  "上": ["au-dessus / haut", 1],
  "無い": ["ne pas y avoir", 1],
  "こう": ["comme ça", 1],
  "呼ぶ": ["appeler", 2],
  "しまう": ["finir / (faire) par erreur", 3],
  "ところ": ["endroit / moment", 2],
  "帰る": ["rentrer / revenir", 2],
  "見える": ["être visible", 2],
  "入れる": ["mettre dedans", 2],
  "受ける": ["recevoir", 2],
  "ただ": ["seulement / juste", 1],
  "生きる": ["vivre", 2],
  "あれ": ["là-bas / ça", 1],
  "よく": ["souvent / bien", 1],
  "金": ["argent / or", 2],
  "わけ": ["raison / motif", 3],
  "好き": ["aimer", 1],
  "少し": ["un peu", 1],
  "全て": ["tout", 2],
  "性": ["sexe / nature", 4],
  "車": ["voiture", 1],
  "先生": ["professeur", 1],
  "でる": ["sortir", 2],
  "込む": ["être rempli / bondé", 3],
  "次": ["suivant", 1],
  "すむ": ["finir / vivre (verbe)", 3],
  "もっと": ["plus", 1],
  "早い": ["rapide / tôt", 1],
  "分": ["minute / fraction", 1],
  "どんな": ["quel type de", 2],
  "もらう": ["recevoir", 2],
  "とる": ["prendre", 1],
  "信ずる": ["croire", 3],
  "教える": ["enseigner", 2],
  "関係": ["relation", 2],
  "間": ["entre / intervalle", 2],
  "名前": ["nom", 1],
  "可能": ["possible", 3],
  "いつ": ["quand", 1],
  "始める": ["commencer", 1],
  "とても": ["très", 1],
  "意味": ["sens / signification", 2],
  "物": ["chose / objet", 2],
  "引く": ["tirer", 2],
  "探す": ["chercher", 2],
  "助ける": ["aider", 2],
  "女": ["femme", 2],
  "度": ["fois / degré", 2],
  "いつも": ["toujours", 1],
  "食べる": ["manger", 1],
  "数": ["nombre", 2],
  "新しい": ["nouveau", 1],
  "家族": ["famille", 2],
  "通り": ["rue", 2],
  "最後": ["dernier", 2],
  "女性": ["femme", 2],
  "情報": ["information", 3],
  "心": ["coeur / esprit", 2],
  "止める": ["arrêter", 2],
  "連れる": ["emmener", 3],
  "心配する": ["s'inquiéter", 3],
  "合う": ["convenir / rencontrer", 2],
  "人々": ["gens", 2],
  "逃げる": ["fuir", 3],
  "別": ["séparé / autre", 2],
  "我": ["moi / nous (litt.)", 4],
  "起きる": ["se réveiller / se produire", 2],
  "落ちる": ["tomber", 2],
  "立つ": ["se tenir / se lever", 2],
  "こっち": ["par ici / ce côté", 1],
  "方法": ["méthode", 2],
  "理由": ["raison", 2],
  "見せる": ["montrer", 2],
  "オレ": ["je (familier)", 3],
  "研究": ["recherche", 3],
  "忘れる": ["oublier", 2],
  "最初": ["le début", 2],
  "守る": ["protéger", 3],
  "すごい": ["formidable / incroyable", 2],
  "ずっと": ["tout le temps / continuellement", 2],
  "二": ["deux", 1],
  "事件": ["incident / affaire", 4],
  "頼む": ["demander / s'il vous plaît", 2],
  "一人": ["une personne / seul", 2],
  "続ける": ["continuer", 2],
  "つまり": ["en d'autres termes", 3],
  "体": ["corps", 2],
  "警察": ["police", 2],
  "人生": ["vie (humaine)", 3],
  "国": ["pays", 2],
  "書く": ["écrire", 1],
  "頭": ["tête", 1],
  "写真": ["photo", 2],
  "顔": ["visage", 2],
  "得る": ["obtenir", 2],
  "全部": ["tout", 2],
  "変わる": ["changer", 2],
  "まま": ["tel quel", 3],
  "終わる": ["finir", 1],
  "上げる": ["donner / élever", 2],
  "部屋": ["pièce / chambre", 1],
  "多く": ["beaucoup", 2],
  "送る": ["envoyer", 2],
  "着く": ["arriver", 2],
  "娘": ["fille (d'une famille)", 2],
  "先": ["avant / précédent", 2],
  "本": ["livre", 1],
  "父": ["père", 1],
  "理解する": ["comprendre", 3],
  "切る": ["couper", 2],
  "あいつ": ["ce type (familier)", 3],
  "覚える": ["se souvenir / mémoriser", 2],
  "息子": ["fils", 1],
  "結婚する": ["se marier", 2],
  "ママ": ["maman", 1],
  "よし": ["très bien / d'accord", 2],
  "飲む": ["boire", 1],
  "会社": ["entreprise", 2],
  "実際": ["en réalité", 3],
  "官": ["officiel / officiel (pref.)", 5],
  "こちら": ["ici / ce côté (poli)", 2],
  "友達": ["ami", 1],
  "バカ": ["idiot / stupide", 2],
  "パパ": ["papa", 1],
  "変える": ["changer (trans.)", 2],
  "願う": ["souhaiter", 3],
  "調べる": ["examiner / rechercher", 3],
  "学校": ["école", 1],
  "重要": ["important", 3],
  "追う": ["poursuivre", 3],
  "捜査": ["enquête", 4],
  "下": ["sous / en bas", 1],
  "どういう": ["quel genre de", 2],
  "是": ["correct / oui (class.)", 6],
  "あと": ["après / plus tard", 1],
  "乗る": ["monter / prendre (transport)", 2],
  "外": ["extérieur", 2],
  "くらい": ["environ / à peu près", 2],
  "かかる": ["prendre (temps, coût)", 2],
  "愛する": ["aimer", 3],
  "ドル": ["dollar", 1],
  "準備": ["préparation", 2],
  "買う": ["acheter", 1],
  "下さる": ["donner (honorifique)", 4],
  "言葉": ["mot / langue", 2],
  "回": ["fois (compteur)", 2],
  "なに": ["quoi", 1],
  "願い": ["souhait", 3],
  "無理": ["impossible / déraisonnable", 3],
  "起こる": ["se produire", 2],
  "強い": ["fort", 2],
  "約束する": ["promettre", 3],
  "確か": ["certain / sûr", 2],
  "連絡": ["contact", 2],
  "働く": ["travailler", 2],
  "大きな": ["grand", 1],
  "素晴らしい": ["merveilleux", 2],
  "一度": ["une fois", 1],
  "相手": ["partenaire / adversaire", 3],
  "夢": ["rêve", 2],
  "安全": ["sécurité / sûr", 2],
  "明日": ["demain", 1],
  "危険": ["danger", 3],
  "やつ": ["type / gars (familier)", 2],
  "うまい": ["délicieux / habile", 2],
  "失う": ["perdre", 2],
  "犯人": ["criminel / coupable", 4],
  "伝える": ["transmettre / informer", 3],
  "おる": ["être (familier / dialect)", 4],
  "機": ["machine / opportunité (préfix)", 4],
  "返す": ["rendre", 2],
  "楽しい": ["amusant", 1],
  "こいつ": ["ce gars (familier)", 3],
  "絶対": ["absolument", 2],
  "どの": ["lequel", 2],
  "質問": ["question", 2],
  "すぎる": ["trop (suffix)", 2],
  "動く": ["bouger", 2],
  "嘘": ["mensonge", 2],
  "説明する": ["expliquer", 3],
  "仲間": ["compagnon / camarade", 3],
  "行う": ["effectuer", 3],
  "怖い": ["effrayant", 2],
  "結果": ["résultat", 2],
  "技術": ["technique / technologie", 4],
  "夜": ["nuit", 1],
  "存在": ["existence", 4],
  "対する": ["envers / contre", 3],
  "まず": ["d'abord", 1],
  "室": ["pièce / chambre (sino-japonais)", 4],
  "会": ["rencontre / réunion (kanji)", 3],
  "月": ["lune / mois", 1],
  "初めて": ["pour la première fois", 2],
  "命": ["vie", 4],
  "最高": ["le meilleur / suprême", 3],
  "置く": ["poser / mettre", 2],
  "残る": ["rester", 2],
  "水": ["eau", 1],
  "長い": ["long", 1],
  "大きい": ["grand", 1],
  "一番": ["le plus / numéro un", 2],
  "状況": ["situation", 3],
  "どれ": ["lequel", 2],
  "高い": ["haut / cher", 2],
  "計画": ["plan", 3],
  "読む": ["lire", 1],
  "病院": ["hôpital", 2],
  "友人": ["ami", 2],
  "学": ["apprendre / étude (kanji)", 4],
  "確認": ["confirmation", 3],
  "向かう": ["se diriger vers", 2],
  "二人": ["deux personnes", 1],
  "聞こえる": ["être entendu", 2],
  "科学": ["science", 4],
  "声": ["voix", 2],
  "部": ["section / département", 3],
  "生活": ["vie quotidienne", 3],
  "用": ["usage / utilité", 3],
  "死": ["mort", 4],
  "簡単": ["facile / simple", 2],
  "場合": ["cas / situation", 2],
  "興味": ["intérêt", 3],
  "行動": ["action / comportement", 3],
  "きっと": ["sûrement", 1],
  "全員": ["tous les membres", 2],
  "ほしい": ["vouloir", 2],
  "ちゃんと": ["correctement / proprement", 2],
  "社会": ["société", 3],
  "名": ["nom / réputation", 3],
  "言える": ["pouvoir dire", 2],
  "チーム": ["équipe", 2],
  "生": ["vivant / brut / cru", 3],
  "番": ["tour / numéro", 2],
  "決める": ["décider", 2],
  "システム": ["système", 3],
  "どうぞ": ["s'il vous plaît / je vous en prie", 1],
  "寝る": ["dormir", 1],
  "深い": ["profond", 3],
  "非常": ["extrêmement / urgence", 3],
  "開ける": ["ouvrir", 2],
  "道": ["route / chemin", 2],
  "去る": ["partir", 3],
  "船": ["bateau", 2],
  "感ずる": ["ressentir (archaïque)", 5],
  "正しい": ["correct", 2],
  "点": ["point", 2],
  "見つかる": ["être trouvé", 2],
  "証拠": ["preuve", 4],
  "離れる": ["s'éloigner", 3],
  "自身": ["soi-même", 3],
  "発見": ["découverte", 4],
  "間違い": ["erreur", 2],
  "宇宙": ["espace / univers", 5],
  "解決": ["résoudre / solution", 4],
  "起こす": ["provoquer / réveiller", 3],
  "考え": ["pensée", 2],
  "飛ぶ": ["voler", 2],
  "父親": ["père", 2],
  "自由": ["liberté", 3],
  "街": ["ville / quartier", 2],
  "多い": ["nombreux", 2],
  "選ぶ": ["choisir", 2],
  "痛い": ["douloureux", 3],
  "最も": ["le plus", 3],
  "母": ["mère", 1],
  "昔": ["autrefois", 3],
  "大事": ["important", 3],
  "患者": ["patient (médecine)", 4],
  "脳": ["cerveau", 4],
  "一体": ["qu'est-ce que ... (étonnement)", 4],
  "急ぐ": ["se dépêcher", 2],
  "敵": ["ennemi", 3],
  "週間": ["semaine", 2],
  "気持ち": ["sentiment / humeur", 2],
  "座る": ["s'asseoir", 2],
  "大学": ["université", 2],
  "捨てる": ["jeter", 2],
  "渡す": ["remettre / donner", 2],
  "大変": ["dur / sérieux", 3],
  "感謝する": ["remercier", 3],
  "野郎": ["salaud / type (vulgaire)", 4],
  "付く": ["être attaché / arriver", 3],
  "普通": ["normal / ordinaire", 2],
  "住む": ["habiter", 2],
  "付ける": ["attacher / appliquer", 2],
  "消える": ["disparaître", 2],
  "失礼": ["impoli / excusez-moi", 3],
  "隠す": ["cacher", 3],
  "最近": ["récemment", 2],
  "件": ["affaire / cas", 3],
  "カード": ["carte", 1],
  "頑張る": ["se donner à fond", 3],
  "妻": ["épouse", 2],
  "データ": ["données", 2],
  "救う": ["sauver", 3],
  "責任": ["responsabilité", 4],
  "今度": ["cette fois / la prochaine fois", 2],
  "員": ["membre / personnel (suffix)", 4],
  "ゲーム": ["jeu", 1],
  "生まれる": ["naître", 2],
  "たくさん": ["beaucoup", 1],
  "全く": ["complètement", 2],
  "小さな": ["petit", 1],
  "状態": ["état / condition", 3],
  "戻す": ["remettre / restituer", 3],
  "感じ": ["sensation / feeling", 2],
  "音": ["son", 1],
  "十分": ["suffisant", 2],
  "さて": ["eh bien / maintenant", 2],
  "元気": ["en forme / santé", 2],
  "終わり": ["fin", 1],
  "幸せ": ["heureux / bonheur", 2],
  "三": ["trois", 1],
  "色": ["couleur", 2],
  "年間": ["annuel", 3],
  "面白い": ["intéressant / drôle", 2],
  "映画": ["film", 2],
  "あんな": ["comme ça (loin)", 2],
  "口": ["bouche", 2],
  "ひどい": ["terrible / sévère", 3],
  "関する": ["concernant", 3],
  "調査": ["investigation / étude", 3],
  "過ぎる": ["passer / dépasser", 2],
  "まさか": ["impossible / pas possible", 3],
  "政府": ["gouvernement", 3],
  "経験": ["expérience", 3],
  "現在": ["actuel / présent", 2],
  "被害": ["dommages / préjudice", 4],
  "元": ["origine / ancien", 3],
  "学ぶ": ["apprendre", 2],
  "残す": ["laisser / laisser derrière", 3],
  "携帯": ["portable / téléphone mobile", 2],
  "払う": ["payer", 2],
  "時代": ["ère / époque", 3],
  "場": ["lieu / emplacement", 3],
  "今夜": ["ce soir", 1],
  "上がる": ["monter", 2],
  "貴方": ["vous (poli)", 2],
  "博士": ["docteur (PhD)", 4],
  "未来": ["futur", 3],
  "王": ["roi", 3],
  "やっぱり": ["comme prévu / après tout", 2],
  "始まる": ["commencer (intr.)", 2],
  "協力": ["coopération", 3],
  "変": ["étrange / changement", 3],
  "刑事": ["détective / officier (police)", 4],
  "母親": ["mère", 2],
  "薬": ["médicament", 3],
  "歩く": ["marcher", 1],
  "似る": ["ressembler", 3],
  "想像": ["imaginer", 3],
  "黙る": ["se taire", 3],
  "光": ["lumière", 2],
  "組織": ["organisation", 3],
  "わたし": ["je / moi (poli)", 1],
  "弁護": ["défense (law)", 5],
  "開く": ["ouvrir", 2],
  "選択": ["choix", 3],
  "完全": ["complet / parfait", 3],
  "答える": ["répondre", 2],
  "怒る": ["se fâcher", 3],
  "逮捕する": ["arrêter (par la police)", 4],
  "昨日": ["hier", 1],
  "影響": ["influence / impact", 3],
  "代": ["ère /代=代? (substitute)", 4],
  "かなり": ["assez / considérablement", 2],
  "記録": ["enregistrement / record", 3],
  "破壊": ["destruction", 4],
  "売る": ["vendre", 2],
  "着る": ["porter (vêtements)", 2],
  "許す": ["permettre / pardonner", 3],
  "犯罪": ["crime", 4],
  "盗む": ["voler (steal)", 3],
  "血": ["sang", 3],
  "戦争": ["guerre", 4],
  "成功": ["succès", 3],
  "利用する": ["utiliser", 3],
  "難しい": ["difficile", 3],
  "カメラ": ["caméra", 2],
  "秘密": ["secret", 3],
  "風": ["vent", 2],
  "ドア": ["porte", 1],
  "気づく": ["remarquer", 2],
  "報告": ["rapport / signaler", 3],
  "客": ["client / invité", 2],
  "現れる": ["apparaître", 2],
  "残念": ["dommage / regrettable", 2],
  "さらに": ["en outre / de plus", 2],
  "例": ["exemple", 2],
  "活動": ["activité", 3],
  "記憶": ["mémoire", 3],
  "治療": ["traitement", 4],
  "過去": ["passé", 3],
  "愛": ["amour", 2],
  "おかしい": ["drôle / étrange", 2],
  "させる": ["faire faire (causer)", 4],
  "真実": ["vérité", 3],
  "少ない": ["peu", 2],
  "価値": ["valeur", 3],
  "ひと": ["personne", 2],
  "捕まえる": ["attraper", 3],
  "認める": ["reconnaître / admettre", 3],
  "真": ["vrai", 3],
  "おまえ": ["toi (rude)", 4],
  "ぐらい": ["environ / à peu près", 2],
  "現実": ["réalité", 3],
  "目的": ["objectif", 3],
  "効果": ["effet", 3],
  "役": ["rôle", 3],
  "内": ["intérieur", 3],
  "生物": ["organisme / être vivant", 4],
  "エネルギー": ["énergie", 3],
  "大統領": ["président", 5],
  "求める": ["demander / rechercher", 3],
  "町": ["ville / bourg", 2],
  "必ず": ["certainement / sans faute", 2],
  "たぶん": ["peut-être", 1],
  "犬": ["chien", 1],
  "レベル": ["niveau", 2],
  "法": ["loi", 3],
  "さっき": ["il y a un moment", 2],
  "変化": ["changement", 3],
  "近く": ["près / proximité", 2],
  "事実": ["fait", 3],
  "男性": ["homme / mâle", 2],
  "能力": ["capacité", 3],
  "朝": ["matin", 1],
  "組む": ["assembler / se lier", 3],
  "事故": ["accident", 3],
  "若い": ["jeune", 1],
  "動物": ["animal", 2],
  "走る": ["courir", 1],
  "間違う": ["se tromper", 2],
  "装置": ["appareil", 3],
  "精神": ["esprit / mental", 4],
  "進む": ["avancer", 2],
  "飛行": ["vol (flight)", 4],
  "全然": ["pas du tout", 2],
  "直す": ["réparer / corriger", 3],
  "以外": ["à part / excepté", 3],
  "張る": ["étirer / coller", 3],
  "答え": ["réponse", 2],
  "美しい": ["beau / belle", 2],
  "突く": ["enfoncer / piquer", 3],
  "やがる": ["(suffixrude) faire", 5],
  "とおり": ["comme / selon", 2],
  "大切": ["important / précieux", 3],
  "自然": ["nature / naturel", 3],
  "共": ["ensemble /共に = ensemble", 4],
  "海": ["mer", 2],
  "無": ["rien / absence", 4],
  "姿": ["apparence / silhouette", 3],
  "特別": ["spécial", 3],
  "示す": ["montrer / indiquer", 3],
  "医者": ["médecin", 2],
  "手伝う": ["aider", 2],
  "打つ": ["frapper / taper", 3],
  "互い": ["mutuellement", 3],
  "書": ["écrire / écriture", 3],
  "失敗": ["échec", 3],
  "命令": ["ordre / commandement", 4],
  "今回": ["cette fois", 2],
  "勝つ": ["gagner", 2],
  "地": ["terre / sol", 3],
  "罪": ["péché / crime", 4],
  "経済": ["économie", 4],
  "警官": ["agent de police", 3],
  "止まる": ["s'arrêter", 2],
  "違い": ["différence", 2],
  "等": ["etc / égal", 3],
  "例えば": ["par exemple", 2],
  "任せる": ["confier", 3],
  "冗談": ["blague", 2],
  "チャンス": ["chance / opportunité", 2],
  "なり": ["devenir / sembler", 3],
  "線": ["ligne", 2],
  "女の子": ["fille", 1],
  "形": ["forme", 2],
  "環境": ["environnement", 3],
  "気分": ["humeur", 2],
  "生徒": ["élève", 2],
  "監視": ["surveillance", 4],
  "あそこ": ["là-bas", 1],
  "回る": ["tourner", 2],
  "紹介する": ["présenter", 3],
  "さま": ["etat / façon / Mr.", 4],
  "移動する": ["se déplacer", 3],
  "壁": ["mur", 2],
  "困る": ["être embêté / avoir un problème", 3],
  "手術": ["chirurgie", 4],
  "唯一": ["unique", 3],
  "後ろ": ["derrière", 2],
  "妹": ["sœur cadette", 2],
  "実験": ["expérience (scientifique)", 4],
  "毎日": ["chaque jour", 1],
  "用意": ["préparation", 2],
  "都市": ["métropole / ville", 3],
  "鍵": ["clé", 2],
  "開発": ["développement", 4],
  "おかげ": ["grâce à", 2],
  "テレビ": ["télévision", 1],
  "食う": ["manger (familier)", 3],
  "種": ["espèce / type", 3],
  "現場": ["site / scène (d'un crime)", 4],
  "一部": ["une partie", 2],
  "番号": ["numéro", 2],
  "子ども": ["enfant", 1],
  "身": ["corps / soi", 3],
  "細胞": ["cellule", 4],
  "運転": ["conduite", 3],
  "続く": ["continuer (intr.)", 2],
  "以前": ["auparavant", 3],
  "主義": ["doctrine / -isme", 4],
  "島": ["île", 2],
  "服": ["vêtements", 2],
  "嬉しい": ["heureux / content", 2],
  "よろしく": ["bien à vous / s'il vous plaît", 2],
  "枚": ["compteur (feuilles)", 3],
  "参加": ["participation", 3],
  "助け": ["aide", 2],
  "信用": ["confiance", 3],
  "裁判": ["procès / tribunal", 4],
  "語": ["langue / mot (suffix)", 3],
  "特に": ["surtout / particulierement", 2],
  "夫": ["mari", 2],
  "奪う": ["arracher / voler", 4],
  "式": ["cérémonie / formule", 3],
  "モンスター": ["monstre", 2],
  "個人": ["individu / personne", 3],
  "泣く": ["pleurer", 2],
  "社長": ["président d'entreprise", 4],
  "原因": ["cause", 3],
  "弟": ["frère cadet", 2],
  "信頼": ["confiance", 3],
  "どっち": ["lequel / lequel des deux", 2],
  "そいつ": ["ce type (familier)", 3],
  "武器": ["arme", 3],
  "音楽": ["musique", 2],
  "済む": ["se terminer / suffire", 3],
  "消す": ["effacer / éteindre", 2],
  "小さい": ["petit", 1],
  "嫌い": ["détester", 2],
  "申し訳": ["excuse / regret", 4],
  "関わる": ["être impliqué", 3],
  "山": ["montagne", 2],
  "まるで": ["comme si", 3],
  "部分": ["partie", 3],
  "しっかり": ["fermement / correctement", 2],
  "両親": ["parents", 2],
  "保護": ["protection", 4],
  "先輩": ["senpai / aîné", 3],
  "州": ["état (province)", 3],
  "太陽": ["soleil", 2],
  "押す": ["pousser / presser", 2],
  "希望": ["espoir / souhait", 3],
  "軍": ["armée", 3],
  "反応": ["réaction", 3],
  "気付く": ["remarquer", 2],
  "決まる": ["être décidé", 2],
  "人物": ["personnalité / personnage", 3],
  "貸す": ["prêter", 2],
  "人類": ["humanité", 4],
  "成長": ["croissance", 3],
  "邪魔": ["gêne / obstruction", 3],
  "マジ": ["sérieux / vraiment (argot)", 3],
  "全体": ["ensemble / totalité", 3],
  "笑う": ["rire", 1],
  "描く": ["dessiner / peindre", 3],
  "本物": ["véritable / authentique", 4],
  "政治": ["politique", 4],
  "駄目": ["inutile / pas bon", 3],
  "意識": ["conscience", 4],
  "木": ["arbre", 2],
  "本気": ["sérieux", 3],
  "限り": ["tant que / limite", 4],
  "運ぶ": ["transporter", 3],
  "医療": ["soins médicaux", 4],
  "花": ["fleur", 2],
  "抜ける": ["s'enlever / sortir", 3],
  "ビデオ": ["vidéo", 2],
  "高校": ["lycée", 3],
  "落とす": ["laisser tomber / laisser tomber (trans)", 3],
  "期待": ["attente / espoir", 3],
  "遺伝": ["génétique", 5],
  "メール": ["email", 1],
  "教育": ["éducation", 4],
  "遊ぶ": ["jouer", 1],
  "管理": ["gestion / management", 4],
  "注意": ["attention / prudence", 2],
  "無事": ["sain et sauf", 2],
  "過ごす": ["passer (du temps)", 2],
  "予定": ["plan / programme", 2],
  "降りる": ["descendre / sortir (transport)", 2],
  "ドラゴン": ["dragon", 2],
  "使える": ["pouvoir être utilisé", 2],
  "取引": ["transaction / affaire", 3],
  "正直": ["honnête", 3],
  "秒": ["seconde", 1],
  "どちら": ["lequel / lequel des deux", 2],
  "不明": ["inconnu", 3],
  "犠牲": ["sacrifice", 4],
  "たった": ["seulement / à peine", 2],
  "傷": ["blessure", 3],
  "立てる": ["ériger / dresser", 3],
  "号": ["numéro / signal", 3],
  "集める": ["rassembler / collecter", 3],
  "歴史": ["histoire (historique)", 4],
  "決して": ["jamais (avec négation)", 3],
  "品": ["article / marchandise", 3],
  "結局": ["finalement", 3],
  "星": ["étoile", 2],
  "親": ["parent", 2],
  "楽しむ": ["profiter / prendre plaisir", 3],
  "銀行": ["banque", 3],
  "当然": ["évidemment / naturel", 3],
  "突然": ["soudain", 2],
  "感情": ["émotion", 3],
  "証明": ["preuve / démonstration", 4],
  "料理": ["cuisine", 3],
  "ボス": ["patron / chef", 2],
  "思える": ["sembler", 3],
  "亡くなる": ["mourir (poli)", 4],
  "従う": ["suivre / obéir", 3],
  "ちょうど": ["juste / exactement", 2],
  "館": ["bâtiment / manoir", 4],
  "無駄": ["inutile / gaspillage", 3],
  "提供する": ["fournir / offrir", 3],
  "耳": ["oreille", 2],
  "負ける": ["perdre (match)", 2],
  "明らか": ["clair / évident", 3],
  "魔法": ["magie", 3],
  "腕": ["bras / habileté", 3],
  "多分": ["probablement", 2],
  "代わり": ["à la place / en remplacement", 3],
  "ロボット": ["robot", 2],
  "少年": ["garçon", 2],
  "古い": ["vieux / ancien", 1],
  "アイデア": ["idée", 2],
  "素敵": ["charmant / joli", 2],
  "結構": ["plutôt / suffisant", 2],
  "あたし": ["je (féminin informel)", 3],
  "爆発": ["explosion", 4],
  "地域": ["région", 3],
  "メッセージ": ["message", 2],
  "あらゆる": ["tous les / chaque", 3],
  "おそらく": ["probablement", 2],
  "合わせる": ["assembler / coordonner", 3],
  "兄": ["frère aîné", 2],
  "連中": ["ces gens (familier)", 3],
  "感じる": ["ressentir", 2],
  "デザイン": ["design", 2],
  "主人": ["maître / propriétaire", 3],
  "ビル": ["bâtiment / immeuble", 2],
  "瞬間": ["moment", 2],
  "傷つける": ["blesser", 3],
  "閉じる": ["fermer", 2],
  "隠れる": ["se cacher", 2],
  "空": ["ciel / vide", 2],
  "健康": ["santé", 3],
  "いくら": ["combien (coût)", 2],
  "企業": ["entreprise / corporation", 3],
  "いろいろ": ["divers / varié", 2],
  "専門": ["spécialité / domaine", 3],
  "感": ["sensation / impression", 3],
  "機能": ["fonctionnalité", 4],
  "戦い": ["combat / bataille", 3],
  "ウソ": ["mensonge (colloq.)", 2],
  "奥さん": ["épouse / madame", 2],
  "生命": ["vie (scientifique)", 4],
  "いっぱい": ["plein / beaucoup", 2],
  "円": ["yen / cercle", 2],
  "映像": ["image / vidéo", 3],
  "リスト": ["liste", 2],
  "大人": ["adulte", 2],
  "忙しい": ["occupé", 2],
  "兄弟": ["frères et soeurs", 2],
  "借りる": ["emprunter", 2],
  "動き": ["mouvement", 2],
  "最悪": ["le pire", 3],
  "赤ちゃん": ["bébé", 1],
  "向こう": ["l'autre côté / là-bas", 2],
  "要る": ["avoir besoin", 2],
  "完璧": ["parfait", 3],
  "機会": ["opportunité", 3],
  "反対": ["opposé / contre", 3],
  "任務": ["mission / tâche", 3],
  "喜ぶ": ["se réjouir", 3],
  "静か": ["calme", 1],
  "嬢": ["mademoiselle / jeune fille (suff)", 4],
  "向ける": ["diriger vers", 3],
  "心臓": ["coeur (organe)", 4],
  "警備": ["sécurité / garde", 3],
  "大好き": ["adorer / aimer beaucoup", 2],
  "倍": ["fois (multiplication)", 3],
  "支配": ["domination / contrôle", 4],
  "作品": ["oeuvre / travail", 3],
  "通す": ["passer à travers", 3],
  "物語": ["histoire / conte", 3],
  "複雑": ["complexe", 4],
  "上手い": ["habile / bon (taste)", 2],
  "個": ["compteur d'objets", 2],
  "自己": ["soi-même", 3],
  "師": ["maître / professeur", 4],
  "捜す": ["chercher (variante)", 2],
  "プログラム": ["programme", 2],
  "ホテル": ["hôtel", 2],
  "器": ["récipient / instrument", 3],
  "マイク": ["microphone", 2],
  "残り": ["reste / reste", 2],
  "ニュース": ["nouvelles", 2],
  "ゆっくり": ["lentement", 1],
  "我が": ["notre (poétique)", 5],
  "少女": ["jeunefille", 2],
  "担当": ["responsable", 3],
  "襲う": ["attaquer", 3],
  "振る": ["secouer / brandir", 3],
  "側": ["côté", 2],
  "神経": ["nerf / nervosité", 4],
  "使用する": ["utiliser", 3],
  "首": ["cou / leader", 3],
  "やっと": ["enfin", 2],
  "優しい": ["gentil / doux", 2],
  "判断": ["jugement", 3],
  "支援": ["soutien", 3],
  "急": ["urgent / rapide", 3],
  "有": ["exister / y avoir", 4],
  "向く": ["se tourner vers", 2],
  "氏": ["Monsieur / nom (form)", 4],
  "そっち": ["là-bas / de ce côté", 2],
  "パーティー": ["fête / parti", 2],
  "半分": ["moitié", 2],
  "まさに": ["exactement", 2],
  "試す": ["essayer / tester", 2],
  "馬鹿": ["idiot", 2],
  "当たる": ["frapper / gagner (lot)", 3],
  "抜く": ["extraire / retirer", 3],
  "周り": ["autour", 2],
  "一方": ["d'un côté", 3],
  "旅": ["voyage", 2],
  "様子": ["état / aspect", 2],
  "生む": ["produire / donner naissance", 3],
  "絵": ["image / peinture", 2],
  "召喚": ["invocation", 5],
  "すでに": ["déjà", 1],
  "近い": ["proche", 1],
  "思い": ["pensée / émotion", 2],
  "基本": ["fondamental / base", 3],
  "親父": ["père (familier)", 3],
  "建物": ["bâtiment", 2],
  "誕生": ["naissance", 3],
  "検査": ["inspection / test", 4],
  "食事": ["repas", 2],
  "通る": ["passer / traverser", 2],
  "学生": ["étudiant", 2],
  "笑": ["rire / sourire", 2],
  "恐怖": ["peur / terreur", 4],
  "作戦": ["stratégie / opération", 4],
  "森": ["forêt", 2],
  "方向": ["direction", 2],
  "意見": ["opinion", 3],
  "下がる": ["baisser / reculer", 3],
  "猫": ["chat", 1],
  "狙う": ["viser", 3],
  "悪魔": ["démon", 4],
  "骨": ["os", 3],
  "プロジェクト": ["projet", 2],
  "暴力": ["violence", 4],
  "勉強する": ["étudier", 1],
  "世話": ["s'occuper / soin", 3],
  "最大": ["maximum", 3],
  "医": ["médecin (abréviation)", 5],
  "市": ["ville / municipalité", 3],
  "申す": ["dire (humble)", 4],
  "魂": ["âme", 4],
  "量": ["quantité", 3],
  "最終": ["final", 3],
  "集中する": ["se concentrer", 3],
  "文化": ["culture", 3],
  "市民": ["citoyen", 3],
  "ブラック": ["black / noir (loan)", 3],
  "触る": ["toucher", 2],
  "同様": ["semblable / similaire", 3],
  "触れる": ["toucher / évoquer", 3],
  "越える": ["dépasser / franchir", 3],
  "しかも": ["de plus / d'ailleurs", 3],
  "離す": ["séparer / lâcher", 3],
  "新た": ["nouveau / renouvelé", 3],
  "酒": ["alcool / sake", 2],
  "要": ["nécessaire / besoin", 3],
  "在": ["exister (class.)", 5],
  "遅れる": ["être en retard", 2],
  "小": ["petit (kanji)", 4],
  "コード": ["code", 2],
  "迎える": ["accueillir", 3],
  "契約": ["contrat", 4],
  "局": ["bureau / station", 4],
  "ご覧": ["regarder (honorifique)", 4],
  "悲しい": ["triste", 2],
  "暮らす": ["vivre / résider", 2],
  "しばらく": ["un moment", 2],
  "動かす": ["bouger (trans.)", 3],
  "殴る": ["frapper / donner un coup", 3],
  "ショー": ["spectacle", 2],
  "ネット": ["net / internet", 2],
  "はっきり": ["clairement", 2],
  "取れる": ["pouvoir être pris / être disponible", 3],
  "みな": ["tout le monde (oral)", 2],
  "了解": ["compris / accord", 2],
  "箱": ["boîte", 1],
  "許可": ["permission / autorisation", 3],
  "諦める": ["abandonner", 3],
  "一生": ["toute la vie", 3],
  "運命": ["destin", 4],
  "モデル": ["modèle", 2],
  "容疑": ["soupçon / accusation", 4],
  "コーヒー": ["café", 1],
  "運動": ["exercice / mouvement", 3],
  "規模": ["échelle / envergure", 4],
  "特定": ["spécifique / particulier", 4],
  "恋": ["amour (romantique)", 3],
  "火": ["feu", 2],
  "眠る": ["dormir", 1],
  "資金": ["fonds / capital", 4],
  "掛ける": ["mettre / suspendre / parier", 3],
  "会議": ["réunion / conférence", 3],
  "居": ["être présent (class.)", 5],
  "語る": ["raconter", 3],
  "特殊": ["spécial / particulier", 4],
  "姉": ["soeur aînée", 2],
  "権利": ["droit", 4],
  "吹く": ["souffler", 2],
  "謝る": ["s'excuser", 2],
  "なくなる": ["disparaître / décéder (poli)", 3],
  "何者": ["quelqu'un / qui (interrog)", 4],
  "事務": ["affaires administratives", 4],
  "速い": ["rapide", 1],
  "正確": ["exact / précis", 3],
  "疑問": ["doute / question", 3],
  "ポイント": ["point / score", 2],
  "歌": ["chanson / chanter", 2],
  "物質": ["matière / substance", 4],
  "曲": ["morceau / chanson", 3],
  "手紙": ["lettre", 2],
  "訓練": ["entraînement", 3],
  "狂う": ["devenir fou", 4],
  "地獄": ["enfer", 4],
  "目標": ["objectif", 3],
  "貴様": ["toi (insulte)", 6],
  "以来": ["depuis (ce temps)", 3],
  "レッド": ["rouge", 2],
  "障害": ["obstacle / handicap", 4],
  "渡る": ["traverser", 3],
  "今朝": ["ce matin", 1],
  "部下": ["subordonné", 3],
  "倒す": ["abattre / renverser", 3],
  "同時": ["simultané", 3],
  "惑星": ["planète", 4],
  "調子": ["condition / état", 2],
  "当時": ["à l'époque", 3],
  "ロック": ["rock (musique)", 2],
  "沢山": ["beaucoup", 1],
  "届く": ["atteindre / être livré", 2],
  "助かる": ["être sauvé / utile", 2],
  "歌う": ["chanter", 2],
  "集まる": ["se rassembler", 2],
  "安心": ["soulagement / sécurité", 2],
  "疑う": ["douter", 3],
  "有名": ["célèbre", 2],
  "文字": ["caractère / texte", 2],
  "そろそろ": ["bientôt / il est temps", 2],
  "鏡": ["miroir", 2],
  "型": ["type / modèle", 2],
  "平和": ["paix", 3],
  "決定": ["décision", 3],
  "直接": ["direct / directement", 3],
  "巨大": ["énorme", 3],
  "施設": ["installation / établissement", 3],
  "晩": ["soirée", 2],
  "ベッド": ["lit", 1],
  "投げる": ["jeter", 2],
  "いらっしゃる": ["venir / être (honorifique)", 4],
  "いま": ["maintenant (variante)", 1],
  "マシン": ["machine", 2],
  "作業": ["travail / tâche", 3],
  "コンピュータ": ["ordinateur", 2],
  "キス": ["baiser", 2],
  "窓": ["fenêtre", 1],
  "ビジネス": ["affaires / business", 2],
  "可愛い": ["mignon", 1],
  "雇う": ["embaucher", 3],
  "それぞれ": ["chacun / respectivement", 2],
  "飛ばす": ["faire voler / lancer", 3],
  "発動": ["activation / déclenchement", 4],
  "異なる": ["différent", 3],
  "電気": ["électricité", 3],
  "追跡する": ["poursuivre / suivre", 4],
  "ミス": ["erreur / faute", 2],
  "外す": ["enlever / ôter", 2],
  "将来": ["avenir", 3],
  "万": ["dix mille / beaucoup", 3],
  "鳥": ["oiseau", 2],
  "通信": ["communication / transmission", 4],
  "病": ["maladie (rare)", 4],
  "依頼": ["demande / requête", 3],
  "右": ["droite", 1],
  "胸": ["poitrine / coeur (fig)", 2],
  "兵士": ["soldat", 3],
  "進化": ["évolution / évolution biologiq", 4],
  "副": ["vice- / auxiliaire", 4],
  "他人": ["autre personne", 3],
  "ルール": ["règle", 2],
  "繰る": ["répéter / tourner (pages)", 4],
  "世紀": ["siècle", 3],
  "事態": ["situation grave", 4],
  "左": ["gauche", 1],
  "壊す": ["casser / détruire", 3],
  "投資": ["investissement", 4],
  "チェックする": ["vérifier", 2],
  "詳しい": ["détaillé / bien informé", 3],
  "化学": ["chimie", 4],
  "手段": ["moyen / méthode", 3],
  "辞める": ["quitter / démissionner", 2],
  "穴": ["trou", 2],
  "自ら": ["soi-même (formel)", 4],
  "一般": ["général", 3],
  "位置": ["position", 3],
  "避ける": ["éviter", 3],
  "苦労する": ["avoir des difficultés", 4],
  "紙": ["papier", 2],
  "扱う": ["manier / traiter", 3],
  "旅行": ["voyage", 2],
  "解放する": ["libérer", 4],
  "リーダー": ["leader / chef", 3],
  "正義": ["justice", 4],
  "到着する": ["arriver", 2],
  "地下": ["souterrain / sous-sol", 3],
  "あるいは": ["ou bien", 2],
  "足りる": ["suffire", 3],
  "単純": ["simple", 2],
  "相談": ["consultation / discuter", 3],
  "平気": ["ne pas s'inquiéter / ça va", 3],
  "指示": ["instruction / directive", 3],
  "侵入": ["intrusion", 4],
  "吸う": ["aspirer / fumer", 2],
  "スピード": ["vitesse", 2],
  "トラック": ["camion / piste", 2],
  "巻く": ["enrouler", 3],
  "危ない": ["dangereux", 2],
  "市場": ["marché", 3],
  "替える": ["remplacer", 3],
  "緊急": ["urgent", 3],
  "もたらす": ["apporter / causer", 4],
  "裏": ["verso / arrière", 3],
  "加える": ["ajouter", 3],
  "隣": ["voisin / à côté", 2],
  "記事": ["article (journal)", 3],
  "永遠": ["éternité", 4],
  "信号": ["signal / feu (trafic)", 3],
  "知識": ["connaissance", 4],
  "行為": ["acte / action", 4],
  "弱い": ["faible", 2],
  "くせ": ["habitude / tic", 4],
  "新聞": ["journal / quotidien", 3],
  "種類": ["type / variété", 3],
  "実行": ["exécution / implémentation", 4],
  "オフィス": ["bureau", 2],
  "頂く": ["recevoir (humble)", 4],
  "南": ["sud", 2],
  "クラブ": ["club", 2],
  "主": ["maître / principal", 4],
  "裏切る": ["trahir", 4],
  "開始": ["commencement", 3],
  "髪": ["cheveux", 2],
  "放す": ["laisser aller / libérer", 3],
  "行方": ["parcours / lieu où se trouve quelqu'un", 4],
  "会話": ["conversation", 2],
  "掃除": ["nettoyage", 2],
  "術": ["technique / art", 4],
  "国家": ["nation / état", 4],
  "壊れる": ["se briser / se casser (intr.)", 3],
  "知れる": ["être connu", 4],
  "増える": ["augmenter", 2],
  "面倒": ["tracas / ennui", 3],
  "死亡": ["décès", 4],
  "つながる": ["être connecté / lié", 3],
  "証言": ["témoignage", 4],
  "偶然": ["par hasard", 3],
  "途中": ["en chemin", 3],
  "発生する": ["survenir / se produire", 4],
  "不思議": ["mystérieux / merveilleux", 3],
  "疲れる": ["être fatigué", 2],
  "デート": ["rendez-vous / date", 2],
  "ファイル": ["fichier", 2],
  "界": ["monde / domaine (suffix)", 4],
  "進める": ["promouvoir / faire avancer", 3],
  "教師": ["enseignant / professeur", 3],
  "ようこそ": ["bienvenu", 2],
  "高": ["haut / élevé", 4],
  "誘う": ["inviter", 3],
  "破る": ["rompre / violer", 3],
  "噂": ["rumeur", 3],
  "回す": ["faire tourner / passer", 3],
  "茶": ["thé", 1],
  "馬": ["cheval", 2],
  "寒い": ["froid", 1],
  "分析": ["analyse", 4],
  "魚": ["poisson", 2],
  "ナイフ": ["couteau", 2],
  "尋ねる": ["demander / interroger", 3],
  "天": ["ciel / paradis (archaic)", 4],
  "内容": ["contenu", 3],
  "中心": ["centre", 3],
  "段階": ["étape / phase", 3],
  "育てる": ["élever / éduquer", 3],
  "身体": ["corps physique", 3],
  "不安": ["inquiétude / anxiété", 3],
  "姉ちゃん": ["grande soeur (familier)", 3],
  "卒業": ["graduation", 3],
  "距離": ["distance", 3],
  "当てる": ["viser / deviner", 3],
  "スター": ["star / célébrité", 2],
  "授業": ["leçon / cours", 2],
  "医師": ["médecin", 4],
  "夕食": ["dîner", 2],
  "一致する": ["coïncider / correspondre", 3],
  "目撃": ["témoignage (voir)", 4],
  "既に": ["déjà", 1],
  "芸術": ["art", 3],
  "構造": ["structure", 4],
  "流す": ["laisser couler / déverser", 3],
  "苦しむ": ["souffrir", 3],
  "ほんの": ["seulement / à peine", 2],
  "ほか": ["autre", 2],
  "異常": ["anormalité", 4],
  "練習": ["pratique / entraînement", 2],
  "インターネット": ["internet", 1],
  "スーツ": ["costume", 2],
  "無し": ["sans", 2],
  "評価": ["évaluation", 3],
  "撮影する": ["filmer / photographier", 3],
  "テクノロジー": ["technologie", 3],
  "もしもし": ["allô (téléphone)", 1],
  "ネットワーク": ["réseau / network", 2],
  "切れる": ["se casser / s'arrêter (fonction)", 3],
  "赤い": ["rouge", 1],
  "かつて": ["jadis / autrefois", 3],
  "最低": ["le plus bas / pire", 3],
  "幸運": ["bonne chance", 2],
  "抱く": ["tenir / câliner / embrasser", 3],
  "望み": ["espérance / espoir", 3],
  "予想": ["prévision / attente", 3],
  "殿": ["monsieur / seigneur (honorific old)", 5],
  "再び": ["à nouveau", 2],
  "兄ちゃん": ["grand frère (familier)", 3],
  "処理": ["traitement / gestion", 3],
  "程度": ["degré / niveau", 3],
  "マーク": ["marque", 2],
  "値": ["valeur / prix", 3],
  "けれど": ["mais / cependant", 2],
  "サービス": ["service", 2],
  "うるさい": ["bruyant / pénible", 2],
  "奇妙": ["étrange", 3],
  "恐ろしい": ["terrifiant", 4],
  "工場": ["usine", 3],
  "知り合い": ["connaissance (personne)", 3],
  "利益": ["profit / intérêt", 3],
  "クラス": ["classe", 2],
  "育つ": ["grandir", 2],
  "慣れる": ["s'habituer", 3],
  "実現する": ["réaliser / accomplir", 4],
  "疲れ": ["fatigue", 2],
  "時々": ["parfois", 1]
};

function estimateLevel(word) {
  if (map[word]) return map[word][1];
  // fallback: 1-5 based on length and kanji count
  const hasKanji = /[\u4e00-\u9faf]/.test(word);
  if (!hasKanji) return 2;
  const len = word.length;
  if (len <= 2) return 2;
  if (len <= 4) return 3;
  return 4;
}

const result = lines.map(w => {
  const entry = map[w];
  if (entry) {
    return { name: w, translation: entry[0], level: entry[1], audioURL: "" };
  }
  return { name: w, translation: "", level: estimateLevel(w), audioURL: "" };
});

fs.writeFileSync(jaPath, JSON.stringify(result, null, 2), 'utf8');
console.log('Wrote', result.length, 'entries to', jaPath);

